"""create initial tokenwatch models

Revision ID: 016212af3ae3
Revises:
Create Date: 2026-06-13 02:05:01.950069

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "016212af3ae3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_pricing",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column(
            "input_cost_per_1k_tokens",
            sa.Numeric(precision=18, scale=10),
            nullable=False,
        ),
        sa.Column(
            "output_cost_per_1k_tokens",
            sa.Numeric(precision=18, scale=10),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_model_pricing_model_name"),
        "model_pricing",
        ["model_name"],
        unique=True,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("api_key_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_api_key_hash"), "users", ["api_key_hash"], unique=True
    )
    op.create_table(
        "ai_request_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("trace_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("endpoint_name", sa.String(length=255), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("prompt_preview", sa.Text(), nullable=False),
        sa.Column("response_preview", sa.Text(), nullable=True),
        sa.Column("prompt_hash", sa.String(length=255), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column(
            "estimated_cost_usd", sa.Numeric(precision=18, scale=10), nullable=False
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_request_logs_created_at"),
        "ai_request_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_request_logs_endpoint_name"),
        "ai_request_logs",
        ["endpoint_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_request_logs_model_name"),
        "ai_request_logs",
        ["model_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_request_logs_prompt_hash"),
        "ai_request_logs",
        ["prompt_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_request_logs_status"), "ai_request_logs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_ai_request_logs_trace_id"),
        "ai_request_logs",
        ["trace_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_ai_request_logs_user_id"), "ai_request_logs", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_request_logs_user_id"), table_name="ai_request_logs")
    op.drop_index(op.f("ix_ai_request_logs_trace_id"), table_name="ai_request_logs")
    op.drop_index(op.f("ix_ai_request_logs_status"), table_name="ai_request_logs")
    op.drop_index(op.f("ix_ai_request_logs_prompt_hash"), table_name="ai_request_logs")
    op.drop_index(op.f("ix_ai_request_logs_model_name"), table_name="ai_request_logs")
    op.drop_index(
        op.f("ix_ai_request_logs_endpoint_name"), table_name="ai_request_logs"
    )
    op.drop_index(op.f("ix_ai_request_logs_created_at"), table_name="ai_request_logs")
    op.drop_table("ai_request_logs")
    op.drop_index(op.f("ix_users_api_key_hash"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_model_pricing_model_name"), table_name="model_pricing")
    op.drop_table("model_pricing")
    # ### end Alembic commands ###
